# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  GREETING: Hello, World!
  BINARY_LOC: bin

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    cmds:
      - go build -o ./{{.BINARY_LOC}}/ -v ./cmd/echo/...
      - go build -o ./{{.BINARY_LOC}}/ -v ./cmd/cat/...
      - go build -o ./{{.BINARY_LOC}}/ -v ./cmd/ls/...
